### ISSUE TITLE
Compatibility with sublevel

### ISSUE THREAD

**Issue by mcollina** [rvagg/node-level-ttl#15]
This module is not compatible with sublevel anymore :(, it complains about missing `isOpen()` methods and so on. However, I'm not sure that compatibility with sublevel is still something we aim to achieve with this.

I also tried running it on top of different 'spaces', but with no luck, I'm not getting the right stuff out if it (I'm using a custom encoding for values).

**Comment by ralphtheninja** [comment]
@mcollina What's the status of this issue?

**Comment by mcollina** [comment]
It will be solved by #25, as we remove level-spaces.

**Comment by ralphtheninja** [comment]
@mcollina #25 is superseded by https://github.com/rvagg/node-level-ttl/pull/27
