### ISSUE TITLE
db._ttl.sub.batch calls level-ttl#batch

### ISSUE THREAD

**Issue by ralphtheninja** [rvagg/node-level-ttl#22]
The `db._ttl.sub.batch` call [`here`](https://github.com/rvagg/node-level-ttl/blob/8010e39885265957ad1ba4df7a50a6f634d7255c/level-ttl.js#L28) ends up calling `level-ttl#batch` [`here`](https://github.com/rvagg/node-level-ttl/blob/8010e39885265957ad1ba4df7a50a6f634d7255c/level-ttl.js#L172) because:

1. `level-updown#_batch` calls `levelup#batch` [`here`](https://github.com/rvagg/level-updown/blob/ad1b985038ed47507821b218e0dc2304389bf0fa/level-updown.js#L223) and
2. `levelup#batch` is rebound by `level-ttl` [`here`](https://github.com/rvagg/node-level-ttl/blob/8010e39885265957ad1ba4df7a50a6f634d7255c/level-ttl.js#L242)

Now, this works because the `options` object doesn't have any `ttl` property set when `level-ttl#batch` is called *internally* (an internal call would be e.g. `db._ttl.sub.batch()`). However, if we want to be able to implement a `defaultTTL` type of use case, this wouldn't work because we would try to put `ttl` information on the ttl keys, which would end up in here again and we have an infinite loop.

This can be addressed in several ways but I'm not entirely sure what the best way is, so I'd like to know your guys opinion on this if you have a minute.

1. Either we add a key check in `level-ttl#batch` to have it ignore ttl meta data keys. This would mean checking against `'\xff'` which is a leaky abstraction on `level-spaces`.
2. Make sure that `level-updown#_batch` always calls the original `levelup#batch` regardless if it has been patched by `level-ttl` or not (see https://github.com/rvagg/level-updown/pull/2)

Thoughts?

/cc @rvagg @ekristen @mcollina @hij1nx

**Comment by ralphtheninja** [comment]
I'm marking this as a bug since it might be a potential bug. It also doesn't feel right that `level-ttl#batch` should be called internally.

**Comment by ekristen** [comment]
I think that if the `batch` has to be called internally that it needs to use the `level-updown#batch` instead of the overloaded version provided by `level-ttl`.

**Comment by ralphtheninja** [comment]
@ekristen I'm not following you.

`level-updown#_batch` calls `levelup#batch` - which it should - but since we overload `levelup#batch` to `level-ttl#batch` we will try to batch the ttl meta keys within `level-ttl#batch` which imo we shouldn't do in the first place, since then we would have to add code to compensate for it when applying `defaultTTL`.

I think the best solution is to make sure `level-updown#_batch` always calls `levelup#batch` (by saving a function bound to it), even if it will be overloaded later, instead of adding code to prevent an unwanted behaviour.

**Comment by ekristen** [comment]
That is what I meant. You clarified it much better than I.

**Comment by ralphtheninja** [comment]
:+1:

**Comment by ekristen** [comment]
PR #25 fixes this.
