### ISSUE TITLE
New release master

### ISSUE THREAD

**Issue by rvagg** [rvagg/node-level-ttl#26]
I have to hand off responsibility for cutting releases on level-ttl, I use it, but it's not important enough for me to keep it all in my head along with all of the other stuff I have going on so I don't want to hold up quality releases or be a reason for poor quality releases.

I'm proposing @mcollina as new release master, I can `npm owner add` him if there are no objections and if he (a) has the time to do this and (b) if this module is important enough to him. My second choice would be @ralphtheninja if @mcollina can't do this I think.

**Comment by ralphtheninja** [comment]
:+1: For @mcollina :)

**Comment by mcollina** [comment]
I am so sorry I have zero bandwidth to do the release master on this project. :+1: for @ralphtheninja!

**Comment by ralphtheninja** [comment]
I'd be happy to help out releasing this module. But I count on your feedback when new pull requests comes in!

**Comment by rvagg** [comment]
done! thanks for stepping up @ralphtheninja, my backlog is insane

**Comment by ralphtheninja** [comment]
:+1:
