### ISSUE TITLE
Breakout ltest() function into separate module?

### ISSUE THREAD

**Issue by ralphtheninja** [rvagg/node-level-ttl#28]
I like the [`ltest()`](https://github.com/rvagg/node-level-ttl/blob/8010e39885265957ad1ba4df7a50a6f634d7255c/test.js#L15-L38) function in `test.js` a lot. It's a very common use case that you want to test something and you want a fresh db, which is closed and cleaned up automatically.

@rvagg Would you mind if I stole your code? :) I'm thinking this would be a good fit together with [`level-test`](https://github.com/dominictarr/level-test) instead of using `levelup` (so there would be automatic support for in memory databases) and it should also probably be slightly more generic, i.e. remove the calls to `ttl()` and `fixtape()` (btw what does that call do?).

Another cool thing would be if it was test agnostic and could be configured with a `test` function, so you could use `tap` or `tape` or whatever.

**Comment by ralphtheninja** [comment]
Obviously that module could be used by `level-ttl` which basically would make the calls to `ttl()` and `fixtape()`.

**Comment by rvagg** [comment]
@ralphtheninja steal whatever you like, I use the same pattern across lots of modules and it probably could be made pretty generic

**Comment by ralphtheninja** [comment]
@rvagg https://github.com/ralphtheninja/ltest

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ ltest@1.0.0
```

**Comment by rvagg** [comment]
sweet, and now the tests have tests!

**Comment by ralphtheninja** [comment]
@rvagg Aye :)
